[PHP]
extension_dir = "c:\Users\Uday Shankar Pandey\Downloads\rescue_coordination\server-env\php\ext"
extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=exif
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip
